image: python:3.4.7-alpine

stages:
  - lint
  - unit
  - package
  - deploy

lint:
  only:
    - develop
  before_script:
    - apk add --update gcc linux-headers musl-dev
    - pip install -r requirements.txt
  stage: lint
  script:
    - prospector
  except:
    - /.*working.*/
  allow_failure: true

unit:
  only:
    - develop
  stage: unit
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m pytest
  except:
    - /.*working.*/
  allow_failure: true

artifactory:
  stage: package
  before_script:
    - apk add --update make zip curl
  script:
    - make build
    - echo ${CI_COMMIT_SHA} | cut -c-7 > dist/version.txt
    - apk add --no-cache --update curl
    - ARTIFACT_FILENAME=aida-insights-$(cat dist/version.txt).tgz
    - tar czvf ${ARTIFACT_FILENAME} dist/
    - curl -i -u${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} -T ${ARTIFACT_FILENAME} "${ARTIFACTORY_URL}/snapshots/aida-insights/${ARTIFACT_FILENAME};revision=${CI_COMMIT_SHA};app=${CI_PROJECT_ID};"
  except:
    - /.*working.*/

.deploy_template: &deploy_template
  stage: deploy
  when: manual
  before_script:
    - apk add --update curl
    - rm -rf dist # make sure nothing left over, we want to deploy only what is downloaded from artifactory
    - pip install awscli
    - curl -u${ARTIFACTORY_USER}:${ARTIFACTORY_PASSWORD} "${ARTIFACTORY_URL}/snapshots/aida-insights/aida-insights-$(echo ${CI_COMMIT_SHA} | cut -c-7).tgz" | tar xz
  except:
    - /.*working.*/

dev_deploy:
  only:
    - develop
  <<: *deploy_template
  script: # --grants=full here to allow gitlab runner from leadid vpc to push artifacts to jornaya s3, and have jornaya-dev users still able to access them.
    - aws s3 sync dist s3://jornaya-dev-us-east-1-aida-insights/pyspark/ --grants=full=id=05f2ef49af03cacb38e69ed08088c8c539de9d897ededd8a75815571b3acab10 --delete
qa_deploy:
  only:
    - master
  <<: *deploy_template
  script:
    - aws s3 sync dist s3://jornaya-qa-us-east-1-aida-insights/pyspark/ --grants=full=id=05f2ef49af03cacb38e69ed08088c8c539de9d897ededd8a75815571b3acab10 --delete
staging_deploy:
  only:
    - master
  <<: *deploy_template
  script:
    - aws s3 sync dist s3://jornaya-staging-us-east-1-aida-insights/pyspark/ --grants=full=id=05f2ef49af03cacb38e69ed08088c8c539de9d897ededd8a75815571b3acab10 --delete
prod_deploy:
  only:
    - master
  <<: *deploy_template
  script:
    - aws s3 sync dist s3://jornaya-prod-us-east-1-aida-insights/pyspark/ --grants=full=id=05f2ef49af03cacb38e69ed08088c8c539de9d897ededd8a75815571b3acab10 --delete

