image: python:3.4.7-alpine

stages:
  - lint
  - unit
  - deploy

lint:
  tags:
    - docker
  before_script:
    - apk add --update gcc linux-headers musl-dev
    - pip --no-cache-dir install -r requirements.txt
  stage: lint
  script:
    - PYTHONPATH=src prospector
  except:
    - /.*working.*/

unit:
  tags:
    - docker
  stage: unit
  before_script:
    - apk add --update bash openjdk8
    - pip --no-cache-dir install -r requirements.txt
  script:
    - python -m pytest
  except:
    - /.*working.*/

.deploy_template: &deploy_template
  stage: deploy
  when: manual
  before_script:
    - apk add --update make zip
    - pip install awscli
  except:
    - /.*working.*/

dev_deploy:
  <<: *deploy_template
  tags:
    - docker
    - jornaya-dev
  script:
    - make deploy-dev

qa_deploy:
  <<: *deploy_template
  tags:
    - docker
    - jornaya-qa
  script:
    - make deploy-qa

staging_deploy:
  <<: *deploy_template
  script:
    - make deploy-staging

prod_deploy:
  <<: *deploy_template
  script:
    - make deploy-prod
